/**
 * Curated animation mode names for FloRo / Neon Attack signs.
 * Mode numbers map 1:1 to BLE M{mode} commands. Not extracted from APK in this
 * session; replace entries when official Neon Attack strings are available.
 */
const MODE_NAME_LIST = [
  'Solid Color',
  'Steady Glow',
  'Soft Pulse',
  'Slow Blink',
  'Quick Flash',
  'Breathing Light',
  'Heartbeat',
  'Candle Flicker',
  'Dim Wave',
  'Bright Surge',
  'Gentle Fade',
  'Night Light',
  'Torch Glow',
  'Ember Warmth',
  'Moonbeam',
  'Starlight Twinkle',
  'Campfire',
  'Lantern Glow',
  'Sunrise Wash',
  'Sunset Fade',
  'Horizon Glow',
  'Left Chase',
  'Right Chase',
  'Center Out',
  'Edge In',
  'Snake Run',
  'Comet Trail',
  'Meteor Strike',
  'Laser Scan',
  'Radar Sweep',
  'Clockwise Spin',
  'Counter Spin',
  'Spiral In',
  'Spiral Out',
  'Wave Left',
  'Wave Right',
  'Ripple Out',
  'Ripple In',
  'Ping Pong',
  'Bounce Back',
  'Pendulum Swing',
  'Rainbow Cycle',
  'Spectrum Flow',
  'Prism Shift',
  'Hue Drift',
  'Color Wheel',
  'Warm Shift',
  'Cool Shift',
  'Magenta Mood',
  'Cyan Dream',
  'Amber Glow',
  'Ruby Pulse',
  'Jade Flow',
  'Violet Haze',
  'Gold Rush',
  'Silver Stream',
  'Copper Shine',
  'Opal Shimmer',
  'Sunset Blend',
  'Ocean Depths',
  'Forest Mist',
  'Block March',
  'Pixel Rain',
  'Matrix Fall',
  'Grid Scan',
  'Chessboard',
  'Barcode Run',
  'Striped Flow',
  'Zebra Pulse',
  'Diamond Flash',
  'Triangle Wave',
  'Hex Grid',
  'Mosaic Tile',
  'Brick Layer',
  'Lattice Glow',
  'Cross Hatch',
  'Dot Matrix',
  'Line Dance',
  'Parallel Run',
  'Interleave',
  'Weave Pattern',
  'Storm Flash',
  'Lightning Bolt',
  'Thunder Roll',
  'Aurora Flow',
  'Northern Lights',
  'Galaxy Spin',
  'Nebula Drift',
  'Cosmic Pulse',
  'Solar Flare',
  'Lunar Phase',
  'Eclipse Fade',
  'Supernova',
  'Black Hole',
  'Star Burst',
  'Comet Shower',
  'Wormhole',
  'Hyperdrive',
  'Warp Speed',
  'Quantum Leap',
  'Plasma Core',
  'Bass Drop',
  'Beat Sync',
  'Rhythm Ride',
  'Tempo Wave',
  'Cadence Flow',
  'Kick Drum',
  'Hi-Hat Spark',
  'Snare Roll',
  'Drop Zone',
  'Build Up',
  'Break Down',
  'Chorus Glow',
  'Verse Dim',
  'Bridge Shift',
  'Hook Flash',
  'Melody Trace',
  'Harmony Blend',
  'Chorus Pulse',
  'Dubstep Wobble',
  'House Groove',
  'Disco Ball',
  'Club Strobe',
  'Rave Mode',
  'Festival Flash',
  'Firework Burst',
  'Sparkler Show',
  'Champagne Pop',
  'Confetti Rain',
  'Laser Party',
  'UV Glow',
  'Blacklight',
  'Neon Jungle',
  'Cyber Rave',
  'Retro Wave',
  'Synthwave',
  'Vapor Trail',
  '80s Flash',
  'Funk Pulse',
  'Disco Fever',
  'Dance Floor',
  'Zen Garden',
  'Meditation',
  'Calm Waters',
  'Deep Breath',
  'Spa Day',
  'Rain Drop',
  'Ocean Wave',
  'Wind Gust',
  'Cloud Drift',
  'Misty Morning',
  'Fog Bank',
  'Twilight Haze',
  'Dream State',
  'Sleep Mode',
  'Lazy Sunday',
  'Cozy Corner',
  'Fireplace',
  'Reading Lamp',
  'Study Glow',
  'Focus Beam',
  'Power Surge',
  'Overdrive',
  'Max Output',
  'Turbo Mode',
  'Nitro Boost',
  'Afterburner',
  'Rampage',
  'Blitz Mode',
  'Shock Wave',
  'Impact Hit',
  'Crusher',
  'Hammer Time',
  'Drill Spin',
  'Saw Blade',
  'Chain Reaction',
  'Domino Fall',
  'Avalanche',
  'Tsunami',
  'Cyclone',
  'Tornado Spin',
  'Demo Loop',
  'Test Pattern',
  'Factory Calibrate',
  'Debug Flash',
  'Pro Mode',
  'Custom Slot A',
  'Custom Slot B',
  'Random Mix',
  'Shuffle Play',
  'Mode Roulette',
  'Surprise Me',
  'Easter Egg',
  'Hidden Gem',
  'Legacy Classic',
  'Vintage Glow',
  'Experimental',
  'Beta Test',
  'Firmware Demo',
  'Full Spectrum',
];

export const MODE_COUNT = MODE_NAME_LIST.length;

export function getModeName(mode) {
  const index = Number(mode) - 1;
  if (index < 0 || index >= MODE_NAME_LIST.length) {
    return `Mode ${mode}`;
  }
  return MODE_NAME_LIST[index];
}

export function formatModeLabel(mode, { compact = false } = {}) {
  const num = Number(mode);
  const name = getModeName(num);
  if (num === 1) {
    return compact ? 'Solid Color' : '1 · Solid Color';
  }
  return compact ? name : `${num} · ${name}`;
}

export function modeMatchesQuery(mode, query) {
  const q = query.trim().toLowerCase();
  if (!q) return true;
  const num = Number(mode);
  const name = getModeName(num).toLowerCase();
  return name.includes(q) || String(num).includes(q) || `mode ${num}`.includes(q);
}

export function listModes({ query = '', limit = 200 } = {}) {
  const results = [];
  for (let mode = 1; mode <= MODE_COUNT; mode += 1) {
    if (!modeMatchesQuery(mode, query)) continue;
    results.push({ mode, name: getModeName(mode), label: formatModeLabel(mode) });
    if (results.length >= limit) break;
  }
  return results;
}
